# Generated by Django 3.2.10 on 2022-02-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, choices=[('FootBall', 'FootBall'), ('Food and Drinks', 'Food and Drinks'), ('Housing and Real Estates', 'Housing and Real Estates')], max_length=300, null=True),
        ),
    ]
