version: '3.8'
services:
  backend:
    image: mathemartins/socialiga-django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "80:8000"
    environment:
      - POSTGRES_DB=socialiga_db
      - POSTGRES_USER=socialiga_db
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_HOST=${RDS_HOST}